# This file is for local development overrides
version: '3.8'

services:
  app:
    environment:
      - "PHP_IDE_CONFIG=serverName=laravel"
      - "XDEBUG_MODE=develop,debug"
      - "XDEBUG_CONFIG=client_host=host.docker.internal"
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini